version: "3.9"
services:
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
    ports:
      - "5432:5432"
  populate-database:
    profiles:
      - initialise
    image: 'postgres'
    depends_on:
      - database
    volumes:
      - ./database_backups:/database_backups
    restart: 'no'
    entrypoint: [ "bash", "-c", " sleep 5 && pg_restore --dbname=postgresql://postgres:MDigital21@database:5432/sequel-mart /database_backups/sequel-mart-20210904-complete"]
  app:
    image: 'node:8'
    user: 'node'
    depends_on:
      - database
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - .:/home/node/app
    ports:
      - '5000:5000'
    command: 'npm start'
volumes:
  database-data: # named volumes can be managed easier using docker-compose
